<?php



/**
 * This class defines the structure of the 'biznes' table.
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Fri Jan  9 02:13:18 2015
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class BiznesTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.BiznesTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('biznes');
        $this->setPhpName('Biznes');
        $this->setClassname('Biznes');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('TITLE', 'Title', 'VARCHAR', false, 255, null);
        $this->addColumn('ADDRESS', 'Address', 'VARCHAR', false, 255, null);
        $this->addColumn('PHONE', 'Phone', 'VARCHAR', false, 100, null);
        $this->addColumn('WEBSITE', 'Website', 'VARCHAR', false, 255, null);
        $this->addColumn('CATEGORY', 'Category', 'VARCHAR', false, 255, null);
        $this->addColumn('PHOTO', 'Photo', 'VARCHAR', true, 255, null);
        $this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('RATING', 'Rating', 'INTEGER', false, null, null);
        $this->addColumn('NUM_COMMENT', 'NumComment', 'INTEGER', false, null, null);
        $this->addColumn('APPROVED', 'Approved', 'BOOLEAN', false, 1, true);
        $this->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'sf_guard_user', 'ID', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('sfGuardUser', 'sfGuardUser', RelationMap::MANY_TO_ONE, array('user_id' => 'id', ), null, null);
        $this->addRelation('BiznesComment', 'BiznesComment', RelationMap::ONE_TO_MANY, array('id' => 'biznes_id', ), 'CASCADE', null, 'BiznesComments');
        $this->addRelation('BiznesTag', 'BiznesTag', RelationMap::ONE_TO_MANY, array('id' => 'biznes_id', ), 'CASCADE', null, 'BiznesTags');
        $this->addRelation('BiznesFav', 'BiznesFav', RelationMap::ONE_TO_MANY, array('id' => 'biznes_id', ), 'CASCADE', null, 'BiznesFavs');
        $this->addRelation('BiznesRate', 'BiznesRate', RelationMap::ONE_TO_MANY, array('id' => 'biznes_id', ), 'CASCADE', null, 'BiznesRates');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
            'symfony_timestampable' => array('create_column' => 'created_at', ),
        );
    } // getBehaviors()

} // BiznesTableMap
