<?php


/**
 * Base class that represents a query for the 'biznes_tag' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Fri Jan  9 05:18:51 2015
 *
 * @method BiznesTagQuery orderByBiznesId($order = Criteria::ASC) Order by the biznes_id column
 * @method BiznesTagQuery orderByUserId($order = Criteria::ASC) Order by the user_id column
 * @method BiznesTagQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method BiznesTagQuery orderByTag($order = Criteria::ASC) Order by the tag column
 * @method BiznesTagQuery orderByNormalizedTag($order = Criteria::ASC) Order by the normalized_tag column
 *
 * @method BiznesTagQuery groupByBiznesId() Group by the biznes_id column
 * @method BiznesTagQuery groupByUserId() Group by the user_id column
 * @method BiznesTagQuery groupByCreatedAt() Group by the created_at column
 * @method BiznesTagQuery groupByTag() Group by the tag column
 * @method BiznesTagQuery groupByNormalizedTag() Group by the normalized_tag column
 *
 * @method BiznesTagQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method BiznesTagQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method BiznesTagQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method BiznesTagQuery leftJoinBiznes($relationAlias = null) Adds a LEFT JOIN clause to the query using the Biznes relation
 * @method BiznesTagQuery rightJoinBiznes($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Biznes relation
 * @method BiznesTagQuery innerJoinBiznes($relationAlias = null) Adds a INNER JOIN clause to the query using the Biznes relation
 *
 * @method BiznesTagQuery leftJoinsfGuardUser($relationAlias = null) Adds a LEFT JOIN clause to the query using the sfGuardUser relation
 * @method BiznesTagQuery rightJoinsfGuardUser($relationAlias = null) Adds a RIGHT JOIN clause to the query using the sfGuardUser relation
 * @method BiznesTagQuery innerJoinsfGuardUser($relationAlias = null) Adds a INNER JOIN clause to the query using the sfGuardUser relation
 *
 * @method BiznesTag findOne(PropelPDO $con = null) Return the first BiznesTag matching the query
 * @method BiznesTag findOneOrCreate(PropelPDO $con = null) Return the first BiznesTag matching the query, or a new BiznesTag object populated from the query conditions when no match is found
 *
 * @method BiznesTag findOneByBiznesId(int $biznes_id) Return the first BiznesTag filtered by the biznes_id column
 * @method BiznesTag findOneByUserId(int $user_id) Return the first BiznesTag filtered by the user_id column
 * @method BiznesTag findOneByCreatedAt(string $created_at) Return the first BiznesTag filtered by the created_at column
 * @method BiznesTag findOneByTag(string $tag) Return the first BiznesTag filtered by the tag column
 * @method BiznesTag findOneByNormalizedTag(string $normalized_tag) Return the first BiznesTag filtered by the normalized_tag column
 *
 * @method array findByBiznesId(int $biznes_id) Return BiznesTag objects filtered by the biznes_id column
 * @method array findByUserId(int $user_id) Return BiznesTag objects filtered by the user_id column
 * @method array findByCreatedAt(string $created_at) Return BiznesTag objects filtered by the created_at column
 * @method array findByTag(string $tag) Return BiznesTag objects filtered by the tag column
 * @method array findByNormalizedTag(string $normalized_tag) Return BiznesTag objects filtered by the normalized_tag column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseBiznesTagQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseBiznesTagQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'BiznesTag', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new BiznesTagQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     BiznesTagQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return BiznesTagQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof BiznesTagQuery) {
            return $criteria;
        }
        $query = new BiznesTagQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj = $c->findPk(array(12, 34), $con);
     * </code>
     *
     * @param array $key Primary key to use for the query
                         A Primary key composition: [$biznes_id, $normalized_tag]
     * @param     PropelPDO $con an optional connection object
     *
     * @return   BiznesTag|BiznesTag[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = BiznesTagPeer::getInstanceFromPool(serialize(array((string) $key[0], (string) $key[1]))))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(BiznesTagPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   BiznesTag A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `BIZNES_ID`, `USER_ID`, `CREATED_AT`, `TAG`, `NORMALIZED_TAG` FROM `biznes_tag` WHERE `BIZNES_ID` = :p0 AND `NORMALIZED_TAG` = :p1';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key[0], PDO::PARAM_INT);
            $stmt->bindValue(':p1', $key[1], PDO::PARAM_STR);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new BiznesTag();
            $obj->hydrate($row);
            BiznesTagPeer::addInstanceToPool($obj, serialize(array((string) $key[0], (string) $key[1])));
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return BiznesTag|BiznesTag[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(array(12, 56), array(832, 123), array(123, 456)), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|BiznesTag[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return BiznesTagQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {
        $this->addUsingAlias(BiznesTagPeer::BIZNES_ID, $key[0], Criteria::EQUAL);
        $this->addUsingAlias(BiznesTagPeer::NORMALIZED_TAG, $key[1], Criteria::EQUAL);

        return $this;
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return BiznesTagQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {
        if (empty($keys)) {
            return $this->add(null, '1<>1', Criteria::CUSTOM);
        }
        foreach ($keys as $key) {
            $cton0 = $this->getNewCriterion(BiznesTagPeer::BIZNES_ID, $key[0], Criteria::EQUAL);
            $cton1 = $this->getNewCriterion(BiznesTagPeer::NORMALIZED_TAG, $key[1], Criteria::EQUAL);
            $cton0->addAnd($cton1);
            $this->addOr($cton0);
        }

        return $this;
    }

    /**
     * Filter the query on the biznes_id column
     *
     * Example usage:
     * <code>
     * $query->filterByBiznesId(1234); // WHERE biznes_id = 1234
     * $query->filterByBiznesId(array(12, 34)); // WHERE biznes_id IN (12, 34)
     * $query->filterByBiznesId(array('min' => 12)); // WHERE biznes_id > 12
     * </code>
     *
     * @see       filterByBiznes()
     *
     * @param     mixed $biznesId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return BiznesTagQuery The current query, for fluid interface
     */
    public function filterByBiznesId($biznesId = null, $comparison = null)
    {
        if (is_array($biznesId) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(BiznesTagPeer::BIZNES_ID, $biznesId, $comparison);
    }

    /**
     * Filter the query on the user_id column
     *
     * Example usage:
     * <code>
     * $query->filterByUserId(1234); // WHERE user_id = 1234
     * $query->filterByUserId(array(12, 34)); // WHERE user_id IN (12, 34)
     * $query->filterByUserId(array('min' => 12)); // WHERE user_id > 12
     * </code>
     *
     * @see       filterBysfGuardUser()
     *
     * @param     mixed $userId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return BiznesTagQuery The current query, for fluid interface
     */
    public function filterByUserId($userId = null, $comparison = null)
    {
        if (is_array($userId)) {
            $useMinMax = false;
            if (isset($userId['min'])) {
                $this->addUsingAlias(BiznesTagPeer::USER_ID, $userId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($userId['max'])) {
                $this->addUsingAlias(BiznesTagPeer::USER_ID, $userId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(BiznesTagPeer::USER_ID, $userId, $comparison);
    }

    /**
     * Filter the query on the created_at column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $createdAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return BiznesTagQuery The current query, for fluid interface
     */
    public function filterByCreatedAt($createdAt = null, $comparison = null)
    {
        if (is_array($createdAt)) {
            $useMinMax = false;
            if (isset($createdAt['min'])) {
                $this->addUsingAlias(BiznesTagPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($createdAt['max'])) {
                $this->addUsingAlias(BiznesTagPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(BiznesTagPeer::CREATED_AT, $createdAt, $comparison);
    }

    /**
     * Filter the query on the tag column
     *
     * Example usage:
     * <code>
     * $query->filterByTag('fooValue');   // WHERE tag = 'fooValue'
     * $query->filterByTag('%fooValue%'); // WHERE tag LIKE '%fooValue%'
     * </code>
     *
     * @param     string $tag The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return BiznesTagQuery The current query, for fluid interface
     */
    public function filterByTag($tag = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($tag)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $tag)) {
                $tag = str_replace('*', '%', $tag);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(BiznesTagPeer::TAG, $tag, $comparison);
    }

    /**
     * Filter the query on the normalized_tag column
     *
     * Example usage:
     * <code>
     * $query->filterByNormalizedTag('fooValue');   // WHERE normalized_tag = 'fooValue'
     * $query->filterByNormalizedTag('%fooValue%'); // WHERE normalized_tag LIKE '%fooValue%'
     * </code>
     *
     * @param     string $normalizedTag The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return BiznesTagQuery The current query, for fluid interface
     */
    public function filterByNormalizedTag($normalizedTag = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($normalizedTag)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $normalizedTag)) {
                $normalizedTag = str_replace('*', '%', $normalizedTag);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(BiznesTagPeer::NORMALIZED_TAG, $normalizedTag, $comparison);
    }

    /**
     * Filter the query by a related Biznes object
     *
     * @param   Biznes|PropelObjectCollection $biznes The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   BiznesTagQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByBiznes($biznes, $comparison = null)
    {
        if ($biznes instanceof Biznes) {
            return $this
                ->addUsingAlias(BiznesTagPeer::BIZNES_ID, $biznes->getId(), $comparison);
        } elseif ($biznes instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(BiznesTagPeer::BIZNES_ID, $biznes->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByBiznes() only accepts arguments of type Biznes or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Biznes relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return BiznesTagQuery The current query, for fluid interface
     */
    public function joinBiznes($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Biznes');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Biznes');
        }

        return $this;
    }

    /**
     * Use the Biznes relation Biznes object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   BiznesQuery A secondary query class using the current class as primary query
     */
    public function useBiznesQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinBiznes($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Biznes', 'BiznesQuery');
    }

    /**
     * Filter the query by a related sfGuardUser object
     *
     * @param   sfGuardUser|PropelObjectCollection $sfGuardUser The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   BiznesTagQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterBysfGuardUser($sfGuardUser, $comparison = null)
    {
        if ($sfGuardUser instanceof sfGuardUser) {
            return $this
                ->addUsingAlias(BiznesTagPeer::USER_ID, $sfGuardUser->getId(), $comparison);
        } elseif ($sfGuardUser instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(BiznesTagPeer::USER_ID, $sfGuardUser->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterBysfGuardUser() only accepts arguments of type sfGuardUser or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the sfGuardUser relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return BiznesTagQuery The current query, for fluid interface
     */
    public function joinsfGuardUser($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('sfGuardUser');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'sfGuardUser');
        }

        return $this;
    }

    /**
     * Use the sfGuardUser relation sfGuardUser object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   sfGuardUserQuery A secondary query class using the current class as primary query
     */
    public function usesfGuardUserQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinsfGuardUser($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'sfGuardUser', 'sfGuardUserQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   BiznesTag $biznesTag Object to remove from the list of results
     *
     * @return BiznesTagQuery The current query, for fluid interface
     */
    public function prune($biznesTag = null)
    {
        if ($biznesTag) {
            $this->addCond('pruneCond0', $this->getAliasedColName(BiznesTagPeer::BIZNES_ID), $biznesTag->getBiznesId(), Criteria::NOT_EQUAL);
            $this->addCond('pruneCond1', $this->getAliasedColName(BiznesTagPeer::NORMALIZED_TAG), $biznesTag->getNormalizedTag(), Criteria::NOT_EQUAL);
            $this->combine(array('pruneCond0', 'pruneCond1'), Criteria::LOGICAL_OR);
        }

        return $this;
    }

}
