_forex:
  enabled:     true
  contextual: true
  with_layout: false   # Default value
  lifetime:    3600   
_weather:
  enabled:     true
  contextual: true
  with_layout: false   # Default value
  lifetime:    1800   
_topnews:
  enabled:     true
  contextual: true
  with_layout: false   # Default value
  lifetime:    36000   
