_topnews:
  enabled:     true
  contextual: true
  with_layout: false   # Default value
  lifetime:    84600   
_newbiznes:
  enabled:     true
  contextual: true
  with_layout: false   # Default value
  lifetime:    84600   
_newbiznessearch:
  enabled:     true
  contextual: true
  with_layout: false   # Default value
  lifetime:    84600   
index:
  enabled:     true
  contextual: true
  with_layout: false   # Default value
  lifetime:    84600   
