showproduct:
  url:   biznes/:id/:title.html
  param: { module: biznes, action: show }
news:
  url:  /:sf_culture/news
  param: {module: content, action: news }
autosuggest:
  url:   /autosuggest
  param: { module: search, action: autosuggest }
biznes_autosuggest:
  url:   /biznes_autosuggest
  param: { module: biznes, action: autosuggest }
map:
  url:  /:sf_culture/map
  param: {module: search, action: map }
  requirements: { sf_culture: (?:az|en|ru) }
submiturl:
  url:  /:sf_culture/submiturl
  param: {module: submiturl, action: index }
collaboration:
  url:  /:sf_culture/collaboration
  param: {module: content, action:collaboration }
contact:
  url:   /:sf_culture/contact
  param: {module: contact, action: create }
  requirements: { sf_culture: (?:az|en|ru) }
about:
  url:   /:sf_culture/about
  param: {module: content, action: about }
  requirements: { sf_culture: (?:az|en|ru) }
investor:
  url:   /:sf_culture/investor
  param: {module: content, action: investor }
  requirements: { sf_culture: (?:az|en|ru) }
faq:
  url:   /:sf_culture/faq
  param: {module: content, action: faq }
  requirements: { sf_culture: (?:az|en|ru) }
copyright:
  url:   /:sf_culture/copyright
  param: { module: content, action: copyright }
ts:
  url:   /:sf_culture/termsofservice
  param: { module: content, action: ts }
privacyp:
  url:   /:sf_culture/privacypolicy
  param: { module: content, action: privacyp }
xeber_index:
  url:  /:sf_culture/xeber
  param: { module:  xeber, action: index }
xeber_search:
  url:  /:sf_culture/xeberaxtar
  param: { module:  xeber, action: searchgr }
biznes_search:
  url:  /:sf_culture/biznesaxtar
  param: { module:  biznes, action: search }
search_www:
  url:  /:sf_culture/axtarwww
  param: { module:  search, action: searchwww }
search_search:
  url:  /:sf_culture/axtar
  param: { module:  search, action: search }
search_site:
  url:  /:sf_culture/axtarsite
  param: { module:  search, action: searchsite }
image_search:
  url:  /:sf_culture/imageaxtar
  param: { module:  search, action: imagesearch }
test_image_search:
  url:  /:sf_culture/testimageaxtar
  param: { module:  search, action: testimagesearch }
test_image_index:
  url:  /:sf_culture/testimage
  param: { module:  search, action: testimageindex }
image_index:
  url:  /:sf_culture/image
  param: { module:  search, action: imageindex }
# default rules
#homepage:
 # url:   /
  #param: { module: default, action: index }
#default_index:
 # url:   /:module
  #param: { action: index }
#default:
 # url:   /:module/:action/*
homepage:
  url:   /
  param: {module: search, action: index }
  requirements: { sf_culture: (?:az|en|ru) }
homepage_culture:
  url:   /:sf_culture
  param: {module: search, action: index }
  requirements: { sf_culture: (?:az|en|ru) }
default_index:
  url:   /:sf_culture/:module
  requirements: { sf_culture: (?:az|en|ru) }
  param: { action: index }
default:
  url:   /:sf_culture/:module/:action/*
  requirements: { sf_culture: (?:az|en|ru) }
