# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false
    cache:                  true
dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .actions:
    #    default_action:         index     # A routing rule doesn't set it
    #
    #    error_404_module:       default   # To be called when a 404 error is raised
    #    error_404_action:       error404  # Or when the requested URL doesn't match any route
    #
    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure


  .settings:
    # Form security secret (CSRF protection)
    #csrf_secret:            eb2febddf974beb2a9cf2082e3571905d9955262
    enabled_modules:        [default, sfLanguageSwitch, profile,sfGuardAuth, sfMediaLibrary, sfGuardGroup, sfGuardUser, sfGuardPermission, sfGuardAuth, sfSimpleForum, sfApply,  sfSocialEvent, sfSocialUser, sfSocialGroup, openInviter,sfSimpleBlog, sfSimpleBlogPostAdmin, sfSimpleBlogCommentAdmin]
    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
     # Charset used for the response
    charset:                utf-8
    # i18n
    i18n: true
    default_culture:        az       # Default user culture
