default:
  http_metas:
    content-type: text/html
  metas:
    title:        axtar search
    description:  new search engine
    keywords:     search, axtar
    language:     en
    robots:       index, follow
  stylesheets:    [/sebekePlugin/css/layout?v=8, main.css?v=50,jquery.qtip.min.css]
  #javascripts:    [jquery.js, jquery.axtar.js?v=7]
  has_layout:     true
  layout:         bootstrap_layout
