default:
  http_metas:
    content-type: text/html
  metas:
    title:        axtar search
    description:  new search engine
    keywords:     search, axtar
    language:     en
    robots:       index, follow
  stylesheets:    [main.css?v=21]
  javascripts:    [jquery.js, jquery.axtar.js?v=7]
  has_layout:     true
  layout:         layout
