<?php


/**
 * Base class that represents a query for the 'sf_social_event' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Fri Jan  9 05:18:54 2015
 *
 * @method sfSocialEventQuery orderById($order = Criteria::ASC) Order by the id column
 * @method sfSocialEventQuery orderByUserAdmin($order = Criteria::ASC) Order by the user_admin column
 * @method sfSocialEventQuery orderByTitle($order = Criteria::ASC) Order by the title column
 * @method sfSocialEventQuery orderByDescription($order = Criteria::ASC) Order by the description column
 * @method sfSocialEventQuery orderByVisibility($order = Criteria::ASC) Order by the visibility column
 * @method sfSocialEventQuery orderByPhoto($order = Criteria::ASC) Order by the photo column
 * @method sfSocialEventQuery orderByStart($order = Criteria::ASC) Order by the start column
 * @method sfSocialEventQuery orderByEnd($order = Criteria::ASC) Order by the end column
 * @method sfSocialEventQuery orderByLocation($order = Criteria::ASC) Order by the location column
 * @method sfSocialEventQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method sfSocialEventQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 *
 * @method sfSocialEventQuery groupById() Group by the id column
 * @method sfSocialEventQuery groupByUserAdmin() Group by the user_admin column
 * @method sfSocialEventQuery groupByTitle() Group by the title column
 * @method sfSocialEventQuery groupByDescription() Group by the description column
 * @method sfSocialEventQuery groupByVisibility() Group by the visibility column
 * @method sfSocialEventQuery groupByPhoto() Group by the photo column
 * @method sfSocialEventQuery groupByStart() Group by the start column
 * @method sfSocialEventQuery groupByEnd() Group by the end column
 * @method sfSocialEventQuery groupByLocation() Group by the location column
 * @method sfSocialEventQuery groupByCreatedAt() Group by the created_at column
 * @method sfSocialEventQuery groupByUpdatedAt() Group by the updated_at column
 *
 * @method sfSocialEventQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method sfSocialEventQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method sfSocialEventQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method sfSocialEventQuery leftJoinsfGuardUser($relationAlias = null) Adds a LEFT JOIN clause to the query using the sfGuardUser relation
 * @method sfSocialEventQuery rightJoinsfGuardUser($relationAlias = null) Adds a RIGHT JOIN clause to the query using the sfGuardUser relation
 * @method sfSocialEventQuery innerJoinsfGuardUser($relationAlias = null) Adds a INNER JOIN clause to the query using the sfGuardUser relation
 *
 * @method sfSocialEventQuery leftJoinsfSocialEventInvite($relationAlias = null) Adds a LEFT JOIN clause to the query using the sfSocialEventInvite relation
 * @method sfSocialEventQuery rightJoinsfSocialEventInvite($relationAlias = null) Adds a RIGHT JOIN clause to the query using the sfSocialEventInvite relation
 * @method sfSocialEventQuery innerJoinsfSocialEventInvite($relationAlias = null) Adds a INNER JOIN clause to the query using the sfSocialEventInvite relation
 *
 * @method sfSocialEventQuery leftJoinsfSocialEventUser($relationAlias = null) Adds a LEFT JOIN clause to the query using the sfSocialEventUser relation
 * @method sfSocialEventQuery rightJoinsfSocialEventUser($relationAlias = null) Adds a RIGHT JOIN clause to the query using the sfSocialEventUser relation
 * @method sfSocialEventQuery innerJoinsfSocialEventUser($relationAlias = null) Adds a INNER JOIN clause to the query using the sfSocialEventUser relation
 *
 * @method sfSocialEventQuery leftJoinEventStatus($relationAlias = null) Adds a LEFT JOIN clause to the query using the EventStatus relation
 * @method sfSocialEventQuery rightJoinEventStatus($relationAlias = null) Adds a RIGHT JOIN clause to the query using the EventStatus relation
 * @method sfSocialEventQuery innerJoinEventStatus($relationAlias = null) Adds a INNER JOIN clause to the query using the EventStatus relation
 *
 * @method sfSocialEvent findOne(PropelPDO $con = null) Return the first sfSocialEvent matching the query
 * @method sfSocialEvent findOneOrCreate(PropelPDO $con = null) Return the first sfSocialEvent matching the query, or a new sfSocialEvent object populated from the query conditions when no match is found
 *
 * @method sfSocialEvent findOneById(int $id) Return the first sfSocialEvent filtered by the id column
 * @method sfSocialEvent findOneByUserAdmin(int $user_admin) Return the first sfSocialEvent filtered by the user_admin column
 * @method sfSocialEvent findOneByTitle(string $title) Return the first sfSocialEvent filtered by the title column
 * @method sfSocialEvent findOneByDescription(string $description) Return the first sfSocialEvent filtered by the description column
 * @method sfSocialEvent findOneByVisibility(int $visibility) Return the first sfSocialEvent filtered by the visibility column
 * @method sfSocialEvent findOneByPhoto(string $photo) Return the first sfSocialEvent filtered by the photo column
 * @method sfSocialEvent findOneByStart(string $start) Return the first sfSocialEvent filtered by the start column
 * @method sfSocialEvent findOneByEnd(string $end) Return the first sfSocialEvent filtered by the end column
 * @method sfSocialEvent findOneByLocation(string $location) Return the first sfSocialEvent filtered by the location column
 * @method sfSocialEvent findOneByCreatedAt(string $created_at) Return the first sfSocialEvent filtered by the created_at column
 * @method sfSocialEvent findOneByUpdatedAt(string $updated_at) Return the first sfSocialEvent filtered by the updated_at column
 *
 * @method array findById(int $id) Return sfSocialEvent objects filtered by the id column
 * @method array findByUserAdmin(int $user_admin) Return sfSocialEvent objects filtered by the user_admin column
 * @method array findByTitle(string $title) Return sfSocialEvent objects filtered by the title column
 * @method array findByDescription(string $description) Return sfSocialEvent objects filtered by the description column
 * @method array findByVisibility(int $visibility) Return sfSocialEvent objects filtered by the visibility column
 * @method array findByPhoto(string $photo) Return sfSocialEvent objects filtered by the photo column
 * @method array findByStart(string $start) Return sfSocialEvent objects filtered by the start column
 * @method array findByEnd(string $end) Return sfSocialEvent objects filtered by the end column
 * @method array findByLocation(string $location) Return sfSocialEvent objects filtered by the location column
 * @method array findByCreatedAt(string $created_at) Return sfSocialEvent objects filtered by the created_at column
 * @method array findByUpdatedAt(string $updated_at) Return sfSocialEvent objects filtered by the updated_at column
 *
 * @package    propel.generator.plugins.sfSocialPlugin.lib.model.om
 */
abstract class BasesfSocialEventQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BasesfSocialEventQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'sfSocialEvent', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new sfSocialEventQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     sfSocialEventQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return sfSocialEventQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof sfSocialEventQuery) {
            return $criteria;
        }
        $query = new sfSocialEventQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   sfSocialEvent|sfSocialEvent[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = sfSocialEventPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(sfSocialEventPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   sfSocialEvent A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `USER_ADMIN`, `TITLE`, `DESCRIPTION`, `VISIBILITY`, `PHOTO`, `START`, `END`, `LOCATION`, `CREATED_AT`, `UPDATED_AT` FROM `sf_social_event` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new sfSocialEvent();
            $obj->hydrate($row);
            sfSocialEventPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return sfSocialEvent|sfSocialEvent[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|sfSocialEvent[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(sfSocialEventPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(sfSocialEventPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(sfSocialEventPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the user_admin column
     *
     * Example usage:
     * <code>
     * $query->filterByUserAdmin(1234); // WHERE user_admin = 1234
     * $query->filterByUserAdmin(array(12, 34)); // WHERE user_admin IN (12, 34)
     * $query->filterByUserAdmin(array('min' => 12)); // WHERE user_admin > 12
     * </code>
     *
     * @see       filterBysfGuardUser()
     *
     * @param     mixed $userAdmin The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function filterByUserAdmin($userAdmin = null, $comparison = null)
    {
        if (is_array($userAdmin)) {
            $useMinMax = false;
            if (isset($userAdmin['min'])) {
                $this->addUsingAlias(sfSocialEventPeer::USER_ADMIN, $userAdmin['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($userAdmin['max'])) {
                $this->addUsingAlias(sfSocialEventPeer::USER_ADMIN, $userAdmin['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(sfSocialEventPeer::USER_ADMIN, $userAdmin, $comparison);
    }

    /**
     * Filter the query on the title column
     *
     * Example usage:
     * <code>
     * $query->filterByTitle('fooValue');   // WHERE title = 'fooValue'
     * $query->filterByTitle('%fooValue%'); // WHERE title LIKE '%fooValue%'
     * </code>
     *
     * @param     string $title The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function filterByTitle($title = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($title)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $title)) {
                $title = str_replace('*', '%', $title);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(sfSocialEventPeer::TITLE, $title, $comparison);
    }

    /**
     * Filter the query on the description column
     *
     * Example usage:
     * <code>
     * $query->filterByDescription('fooValue');   // WHERE description = 'fooValue'
     * $query->filterByDescription('%fooValue%'); // WHERE description LIKE '%fooValue%'
     * </code>
     *
     * @param     string $description The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function filterByDescription($description = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($description)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $description)) {
                $description = str_replace('*', '%', $description);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(sfSocialEventPeer::DESCRIPTION, $description, $comparison);
    }

    /**
     * Filter the query on the visibility column
     *
     * Example usage:
     * <code>
     * $query->filterByVisibility(1234); // WHERE visibility = 1234
     * $query->filterByVisibility(array(12, 34)); // WHERE visibility IN (12, 34)
     * $query->filterByVisibility(array('min' => 12)); // WHERE visibility > 12
     * </code>
     *
     * @param     mixed $visibility The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function filterByVisibility($visibility = null, $comparison = null)
    {
        if (is_array($visibility)) {
            $useMinMax = false;
            if (isset($visibility['min'])) {
                $this->addUsingAlias(sfSocialEventPeer::VISIBILITY, $visibility['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($visibility['max'])) {
                $this->addUsingAlias(sfSocialEventPeer::VISIBILITY, $visibility['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(sfSocialEventPeer::VISIBILITY, $visibility, $comparison);
    }

    /**
     * Filter the query on the photo column
     *
     * Example usage:
     * <code>
     * $query->filterByPhoto('fooValue');   // WHERE photo = 'fooValue'
     * $query->filterByPhoto('%fooValue%'); // WHERE photo LIKE '%fooValue%'
     * </code>
     *
     * @param     string $photo The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function filterByPhoto($photo = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($photo)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $photo)) {
                $photo = str_replace('*', '%', $photo);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(sfSocialEventPeer::PHOTO, $photo, $comparison);
    }

    /**
     * Filter the query on the start column
     *
     * Example usage:
     * <code>
     * $query->filterByStart('2011-03-14'); // WHERE start = '2011-03-14'
     * $query->filterByStart('now'); // WHERE start = '2011-03-14'
     * $query->filterByStart(array('max' => 'yesterday')); // WHERE start > '2011-03-13'
     * </code>
     *
     * @param     mixed $start The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function filterByStart($start = null, $comparison = null)
    {
        if (is_array($start)) {
            $useMinMax = false;
            if (isset($start['min'])) {
                $this->addUsingAlias(sfSocialEventPeer::START, $start['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($start['max'])) {
                $this->addUsingAlias(sfSocialEventPeer::START, $start['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(sfSocialEventPeer::START, $start, $comparison);
    }

    /**
     * Filter the query on the end column
     *
     * Example usage:
     * <code>
     * $query->filterByEnd('2011-03-14'); // WHERE end = '2011-03-14'
     * $query->filterByEnd('now'); // WHERE end = '2011-03-14'
     * $query->filterByEnd(array('max' => 'yesterday')); // WHERE end > '2011-03-13'
     * </code>
     *
     * @param     mixed $end The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function filterByEnd($end = null, $comparison = null)
    {
        if (is_array($end)) {
            $useMinMax = false;
            if (isset($end['min'])) {
                $this->addUsingAlias(sfSocialEventPeer::END, $end['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($end['max'])) {
                $this->addUsingAlias(sfSocialEventPeer::END, $end['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(sfSocialEventPeer::END, $end, $comparison);
    }

    /**
     * Filter the query on the location column
     *
     * Example usage:
     * <code>
     * $query->filterByLocation('fooValue');   // WHERE location = 'fooValue'
     * $query->filterByLocation('%fooValue%'); // WHERE location LIKE '%fooValue%'
     * </code>
     *
     * @param     string $location The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function filterByLocation($location = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($location)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $location)) {
                $location = str_replace('*', '%', $location);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(sfSocialEventPeer::LOCATION, $location, $comparison);
    }

    /**
     * Filter the query on the created_at column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $createdAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function filterByCreatedAt($createdAt = null, $comparison = null)
    {
        if (is_array($createdAt)) {
            $useMinMax = false;
            if (isset($createdAt['min'])) {
                $this->addUsingAlias(sfSocialEventPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($createdAt['max'])) {
                $this->addUsingAlias(sfSocialEventPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(sfSocialEventPeer::CREATED_AT, $createdAt, $comparison);
    }

    /**
     * Filter the query on the updated_at column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedAt('2011-03-14'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt('now'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt(array('max' => 'yesterday')); // WHERE updated_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $updatedAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function filterByUpdatedAt($updatedAt = null, $comparison = null)
    {
        if (is_array($updatedAt)) {
            $useMinMax = false;
            if (isset($updatedAt['min'])) {
                $this->addUsingAlias(sfSocialEventPeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($updatedAt['max'])) {
                $this->addUsingAlias(sfSocialEventPeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(sfSocialEventPeer::UPDATED_AT, $updatedAt, $comparison);
    }

    /**
     * Filter the query by a related sfGuardUser object
     *
     * @param   sfGuardUser|PropelObjectCollection $sfGuardUser The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   sfSocialEventQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterBysfGuardUser($sfGuardUser, $comparison = null)
    {
        if ($sfGuardUser instanceof sfGuardUser) {
            return $this
                ->addUsingAlias(sfSocialEventPeer::USER_ADMIN, $sfGuardUser->getId(), $comparison);
        } elseif ($sfGuardUser instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(sfSocialEventPeer::USER_ADMIN, $sfGuardUser->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterBysfGuardUser() only accepts arguments of type sfGuardUser or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the sfGuardUser relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function joinsfGuardUser($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('sfGuardUser');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'sfGuardUser');
        }

        return $this;
    }

    /**
     * Use the sfGuardUser relation sfGuardUser object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   sfGuardUserQuery A secondary query class using the current class as primary query
     */
    public function usesfGuardUserQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinsfGuardUser($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'sfGuardUser', 'sfGuardUserQuery');
    }

    /**
     * Filter the query by a related sfSocialEventInvite object
     *
     * @param   sfSocialEventInvite|PropelObjectCollection $sfSocialEventInvite  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   sfSocialEventQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterBysfSocialEventInvite($sfSocialEventInvite, $comparison = null)
    {
        if ($sfSocialEventInvite instanceof sfSocialEventInvite) {
            return $this
                ->addUsingAlias(sfSocialEventPeer::ID, $sfSocialEventInvite->getEventId(), $comparison);
        } elseif ($sfSocialEventInvite instanceof PropelObjectCollection) {
            return $this
                ->usesfSocialEventInviteQuery()
                ->filterByPrimaryKeys($sfSocialEventInvite->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterBysfSocialEventInvite() only accepts arguments of type sfSocialEventInvite or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the sfSocialEventInvite relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function joinsfSocialEventInvite($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('sfSocialEventInvite');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'sfSocialEventInvite');
        }

        return $this;
    }

    /**
     * Use the sfSocialEventInvite relation sfSocialEventInvite object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   sfSocialEventInviteQuery A secondary query class using the current class as primary query
     */
    public function usesfSocialEventInviteQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinsfSocialEventInvite($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'sfSocialEventInvite', 'sfSocialEventInviteQuery');
    }

    /**
     * Filter the query by a related sfSocialEventUser object
     *
     * @param   sfSocialEventUser|PropelObjectCollection $sfSocialEventUser  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   sfSocialEventQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterBysfSocialEventUser($sfSocialEventUser, $comparison = null)
    {
        if ($sfSocialEventUser instanceof sfSocialEventUser) {
            return $this
                ->addUsingAlias(sfSocialEventPeer::ID, $sfSocialEventUser->getEventId(), $comparison);
        } elseif ($sfSocialEventUser instanceof PropelObjectCollection) {
            return $this
                ->usesfSocialEventUserQuery()
                ->filterByPrimaryKeys($sfSocialEventUser->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterBysfSocialEventUser() only accepts arguments of type sfSocialEventUser or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the sfSocialEventUser relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function joinsfSocialEventUser($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('sfSocialEventUser');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'sfSocialEventUser');
        }

        return $this;
    }

    /**
     * Use the sfSocialEventUser relation sfSocialEventUser object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   sfSocialEventUserQuery A secondary query class using the current class as primary query
     */
    public function usesfSocialEventUserQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinsfSocialEventUser($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'sfSocialEventUser', 'sfSocialEventUserQuery');
    }

    /**
     * Filter the query by a related EventStatus object
     *
     * @param   EventStatus|PropelObjectCollection $eventStatus  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   sfSocialEventQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByEventStatus($eventStatus, $comparison = null)
    {
        if ($eventStatus instanceof EventStatus) {
            return $this
                ->addUsingAlias(sfSocialEventPeer::ID, $eventStatus->getEventId(), $comparison);
        } elseif ($eventStatus instanceof PropelObjectCollection) {
            return $this
                ->useEventStatusQuery()
                ->filterByPrimaryKeys($eventStatus->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterByEventStatus() only accepts arguments of type EventStatus or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the EventStatus relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function joinEventStatus($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('EventStatus');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'EventStatus');
        }

        return $this;
    }

    /**
     * Use the EventStatus relation EventStatus object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   EventStatusQuery A secondary query class using the current class as primary query
     */
    public function useEventStatusQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinEventStatus($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'EventStatus', 'EventStatusQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   sfSocialEvent $sfSocialEvent Object to remove from the list of results
     *
     * @return sfSocialEventQuery The current query, for fluid interface
     */
    public function prune($sfSocialEvent = null)
    {
        if ($sfSocialEvent) {
            $this->addUsingAlias(sfSocialEventPeer::ID, $sfSocialEvent->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
