_popularnews:
  enabled:     true
  contextual: true
  with_layout: false   # Default value
  lifetime:    1200   
_acarsozler:
  enabled:     true
  contextual: true
  with_layout: false   # Default value
  lifetime:    84600   
_sponsorads:
  enabled:     true
  contextual: true
  with_layout: false   # Default value
  lifetime:    84600   
_topnewswithimagesmainpage:
  enabled:     true
  contextual: true
  with_layout: false   # Default value
  lifetime:    84600   
_topnewswithimagesxeber:
  enabled:     true
  contextual: true
  with_layout: false   # Default value
  lifetime:    84600   
#index:
  #enabled:     true
  #with_layout: false   # Default value
  #lifetime:    84600
  #topnewswithimagesmainpage.php
  #-rw-rw-r--. 1 kingson kingson 2045 Jan 16 01:09 _topnewswithimagesxeber.php
  #
#_topnews:
 # enabled:     true
 # contextual: true
 # with_layout: false   # Default value
  #lifetime:    84600   
