generator:
  class: sfPropelGenerator
  param:
    model_class:           Search
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          search
    with_propel_route:     1
    config:
      actions: ~
      fields:  ~
      list:
        max_per_page: 20
        batch_actions:
          delete: ~
          edit: ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
