<?php



/**
 * Skeleton subclass for performing query and update operations on the 'xeber_num_comment' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Thu May 12 00:23:03 2016
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class XeberNumCommentPeer extends BaseXeberNumCommentPeer
{
}
