propel:
  advertise:
    _attributes:  {idMethod:  native }
    id:  {  type: INTEGER, required:  true,  autoIncrement: true, primaryKey: true  }
    name:  {  type:  VARCHAR, size: 100, required:  true  }
    company:  {  type:  VARCHAR, size: 100, required:  true  }
    email:  {  type:  VARCHAR, size: 100, required:  true  }
    phone:  {  type:  VARCHAR, size: 15, required:  true  }
    comment: {  type:  LONGVARCHAR }
    created_at: {  type: TIMESTAMP  }
  search:
    _attributes:  {idMethod:  native  }
    id:  {  type: INTEGER, required:  true,  autoIncrement: true, primaryKey: true  }
    query:  {type:  VARCHAR, size: 256}
    raw_ip:  { type: VARCHAR, size: 50  }
    created_at: {  type: TIMESTAMP  }
  biznes_search:
    _attributes:  {idMethod:  native  }
    id:  {  type: INTEGER, required:  true,  autoIncrement: true, primaryKey: true  }
    query:  {type:  VARCHAR, size: 256}
    raw_ip:  { type: VARCHAR, size: 50  }
    created_at: {  type: TIMESTAMP  }
  biznes_stat:
    _attributes:  {idMethod:  native  }
    id:  {  type: INTEGER, required:  true,  autoIncrement: true, primaryKey: true  }
    biznes_id: { type: INTEGER, required: true, foreignTable: biznes, foreignReference: id, required: true, onDelete: cascade }
    type:  {type:  VARCHAR, size: 256}
    user_ip:  { type: VARCHAR, size: 50  }
    created_at: {  type: TIMESTAMP  }
  url:
    _attributes:  {idMethod:  native  }
    id:  {  type: INTEGER, required:  true,  autoIncrement: true, primaryKey: true  }
    name:  {type:  VARCHAR, size: 256, required:  true}
    created_at: {  type: TIMESTAMP  }
  sponsor:
    _attributes:  {idMethod:  native  }
    id:  {  type: INTEGER, required:  true,  autoIncrement: true, primaryKey: true  }
    url:  {type:  VARCHAR, size: 256, required: true}
    description: {type:LONGVARCHAR }
    start:       {type:date, required:true }
    end:         {type:date, required:true }
    email:  {type:  VARCHAR, size: 100, required: true  }
    phone:  {type:  VARCHAR, size: 15 }
    comment: {type:  LONGVARCHAR }
    payment:  {type:TINYINT, size: 4, default:0}
    created_at: {type: timestamp }
  keyphrase:
    _attributes:  {idMethod:  native  }
    id:  {  type: INTEGER, required:  true,  autoIncrement: true, primaryKey: true  }
    keyphrase:  {type:  VARCHAR, size: 256, required:  true}
    count:  {  type: INTEGER  }
    active:  {  type: BOOLEAN, default:0  }
    created_at: {  type: TIMESTAMP  }
  biznes:
    _attributes:  {idMethod:  native  }
    id: { type: INTEGER, required: true, autoIncrement: true, primaryKey: true }
    title:  { type: VARCHAR, size: 255 , required: true}
    address: { type: varchar, size: 255 , required: true}
    description: {type:LONGVARCHAR }
    phone: { type: varchar, size: 100 }
    website: { type: varchar, size: 255 }
    email: { type: varchar, size: 255 }
    category: { type: varchar, size: 255 }
    photo: { type: VARCHAR, size: 255 }
    created_at: ~
    approved:  { type: BOOLEAN, default: 0 }
    rating: { type: INTEGER }
    user_id: { type: integer, foreignTable: sf_guard_user, foreignReference: id  }
  biznes_comment:
    _attributes:  {idMethod:  native  }
    biznes_id: { type: INTEGER, required: true, foreignTable: biznes, foreignReference: id, required: true, onDelete: cascade }
    id: { type: INTEGER, required: true, autoIncrement: true, primaryKey: true}
    comment: { type: LONGVARCHAR }
    score:  {  type:integer  }
    created_at: ~
    raw_ip:  { type: VARCHAR, size: 50  }
    user_id: { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
  biznes_tag:
    biznes_id: { type: INTEGER, required: true, primaryKey: true, foreignTable: biznes, foreignReference: id, required: true, onDelete: cascade }
    user_id:  { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    created_at: ~
    tag: { type: VARCHAR, size: 100  }
    normalized_tag: { type: VARCHAR, size: 100, required: true,       primaryKey: true, index: true }
  country:
    _attributes: { idMethod:  native }
    id: { type: INTEGER, size: '10', primaryKey: true, required: true, defaultValue: '0' }
    name: { type: VARCHAR, size: '64', required: true, defaultValue: '' }
    iso_code_2: { type: CHAR, size: '2', required: true, defaultValue: '' }
    iso_code_3: { type: CHAR, size: '3', required: true, defaultValue: '' }
    address_format_id: { type: INTEGER, size: '10', required: true, defaultValue: '0' }
