generator:
  class: sfPropelGenerator
  param:
    model_class:           Biznes
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              Biznes
    plural:                Bizness
    route_prefix:          biznes
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        user_id:
          credentials: [super_admin]
        approved:
          credentials: [super_admin]
      list:    ~
      filter:  ~
      form:    ~
      edit: 
        display: ~
        #display: [title, description, phone, user_id, approved]
        fields:
          title:
            credentials: [super_admin]
          user_id:
            credentials: [super_admin]
          approved:
            credentials: [super_admin]
      new:     ~
