<?php


/**
 * This class adds structure of 'sf_social_event' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Sep 29 17:08:37 2012
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfSocialPlugin.lib.model.map
 */
class sfSocialEventMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfSocialPlugin.lib.model.map.sfSocialEventMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(sfSocialEventPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(sfSocialEventPeer::TABLE_NAME);
		$tMap->setPhpName('sfSocialEvent');
		$tMap->setClassname('sfSocialEvent');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('USER_ADMIN', 'UserAdmin', 'INTEGER', 'sf_guard_user', 'ID', true, null);

		$tMap->addColumn('TITLE', 'Title', 'VARCHAR', true, null);

		$tMap->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', true, null);

		$tMap->addColumn('VISIBILITY', 'Visibility', 'TINYINT', true, null);

		$tMap->addColumn('PHOTO', 'Photo', 'VARCHAR', false, 50);

		$tMap->addColumn('START', 'Start', 'TIMESTAMP', false, null);

		$tMap->addColumn('END', 'End', 'TIMESTAMP', false, null);

		$tMap->addColumn('LOCATION', 'Location', 'VARCHAR', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // sfSocialEventMapBuilder
