about:
  enabled:     true
copyright:
  enabled:     true
ts:
  enabled:     true
privacyp:
  enabled:     true
contact:
  enabled:     true
unavailable:
  enabled:     true    
  with_layout: true   # Default value
  lifetime:    300   # Default value
